export const initialState = {
  // id: 0,
  //statusId: 1,
  totalLaborers: 0,
  safetyHygieneWorkers: 0,
  healthWorkers:0,
  femaleWorkers: 0,
  heavyDangerousWorkers: 0,
  minorWorkers:0,
  workersUnder15: 0,
  disabledWorkers: 0,
  elderlyWorkers: 0,

  totalAccidents: 0,
  fatalAccidents: 0,
  totalLaborAccidents: 0,
  laborDeaths: 0,
  totalAccidentCost: 0,
  propertyDamageCost: 0,
  daysOff: 0,

  totalCumulativeCases: 0,
  newCases: 0,
  daysOffDueToDisease: 0,
  earlyRetirementsDueToDisease: 0,
  totalDiseaseCost: 0,

  typeI: 0,
  typeII: 0,
  typeIII: 0,
  typeIV: 0,
  typeV: 0,

  totalTypeITrained:'0/0',
  totalTypeIITrained: '0/0',
  totalTypeIIITrained: '0/0',
  selfTraining:'0/0',
  hiredTraining: '0/0',
  totalTypeIVTrained: '0/0',
  totalTypeVTrained: '0/0',
  totalTypeVITrained: '0/0',
  totalTrainingCost: 0,

  totalMachines: 0,
  machinesInUse: 0,
  inspectedMachines: 0,
  uninspectedMachines: 0,
  declaredMachines: 0,
  undeclaredMachines: 0,

  partTimeLaborers: 0,
  totalOvertimeHours: 0,
  highestWorkingHours:0,

  totalLaborersHazard: 0,
  totalCost: 0,

  totalSamples: 0,
  nonStandardSamples: 0,
  temperatureSamples: '0/0',
  humiditySamples: '0/0',
  windSpeedSamples: '0/0',
  lightSamples: '0/0',
  noiseSamples: '0/0',
  dustSamples: '0/0',
  vibrationSamples: '0/0',
  toxicGasSamples: '0/0',
  radiationSamples: '0/0',
  electromagneticSamples: '0/0',
  otherSamples: '0/0',

  technicalSafetyMeasures: 0,
  technicalHygieneMeasures: 0,
  personalProtectiveEquipment: 0,
  workerHealthCare:0,
  trainingAndAwareness: 0,
  riskAssessmentSafetyHygiene: 0,
  otherCosts: 0,

  healthServiceProvider: '',
  safetyHygieneServiceProvider: '',
  
  riskAssessmentDate: '',
};
