// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import SideNav from "./components/Home/side-nav";
// import { usePathname } from 'next/navigation';
// // import { ThemeProvider } from "@emotion/react";
// // import theme from "./components/theme";
// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
  
//   return (
//     <html lang="en">
//       <body>
        // <div className="flex h-screen md:flex-row md:overflow-hidden">
        //   {/* Thay đổi chiều rộng của SideNav để chiếm 15% chiều rộng */}
        //   <div className="side-nav left-0 top-0 w-60 h-full bg-[#14317F] m-0 p-0" >
        //     <SideNav />
        //   </div>
        //   <div className="flex-grow px-2 md:overflow-y-auto bg-white">
        //     {children}
        //   </div>
        // </div>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DTI System",
  description: "Generated by VNA Group 4",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
